### ISSUE TITLE
Filter products?

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-snipcart#12]
Hello,
Your plugin just works great!!! 
I would just need a little help with a filter-function:
I'm working on a wineshop where I have 4 major categories "Red", "white", "rosé" & "champagne"...
On my website I also have a page about the different wineyards, and now I would like to link the wineyards to their respective wines in the shop but the wines are spreaded in all categories. Is there any way to tag a wine by putting in the snipcart_detail.md something like
taxonomy:
    tag: [wine, red wine]
    wineyard: oliver
And then set a link on the wineyard-page to a shop-page that shows me all the products of this wineyard?
For ex. a link that would look like:
test.com/shop/tags:oliver
Could you help me please?
Thanks,
Oliver

**Comment by flaviocopes** [comment]
This is a question that involves Taxonomies https://learn.getgrav.org/content/taxonomy and Collections.

It's surely doable by creating a Wines page that lists a Collection, that can be filtered by tag. I would start with the "Blog site" skeleton and think of wines as blog posts, and apply the same concepts.
