### ISSUE TITLE
number of decimal places

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-snipcart#13]
Hello,
I want to show my prices with 2 decimal places after the commata ex: 9,60 €
But if the last decimal is a zero it's cut off and shows: 9,6 €
Where do I need to change it to show both decimals even if it is a 0?
Thanks
Oliver

**Comment by rhukster** [comment]
You should use the number_format filter http://twig.sensiolabs.org/doc/2.x/filters/number_format.html

**Comment by prinla** [comment]
Where can I find it? Or change it? Or put it?

**Comment by flaviocopes** [comment]
I think this is the place: https://github.com/getgrav/grav-plugin-snipcart/blob/develop/templates/partials/snipcart_detail_item.html.twig#L21

**Comment by prinla** [comment]
On the snip_detail_item.html.twig I added **data-item-price="{{ page.header.price }}|number_format(2, '.', ',')"** but that doesn't change anything. Do I have to do anything else?

Very sorry for disturbing you that much... but as I almost contacted "rhukster" at Trilby Media maybe it's even better considering that under a possible training/support from Trilby. I'll try to get in touch by skype with you guys...

**Comment by prinla** [comment]
Forget  my last comment ... I found it !!!

**Comment by prinla** [comment]
The response is to add **|number_format(2, '.', ',')** after page.header.price on https://github.com/getgrav/grav-plugin-snipcart/blob/develop/templates/partials/snipcart_detail_item.html.twig#L13

You can closed the issue ... Thanks guys!!!
