### ISSUE TITLE
Subscription Item Template does not match Snipcart API

### ISSUE THREAD

**Issue by bredmor** [getgrav/grav-plugin-snipcart#21]
Judging from the commit dates on the Repo, I don't know if this plugin is still actively developed at all, but the snipcart requirements for defining subscription plans has changed.

https://docs.snipcart.com/configuration/recurring-and-subscription-plans-definition

Instead of using 'data-plan-name', 'data-plan-id', etc, Snipcart now expects subscriptions to be defined the same as items - just with 'data-item-payment-interval' and 2 other optional attributes defined.

**Comment by jeubanks** [comment]
Any updates on this?  Is this plugin still active?

**Comment by rhukster** [comment]
Sorry, just too  many plugins to keep my eye on.  I'll get around to updating this soon.

Pull requests are always welcome to speed things along...

**Comment by jeubanks** [comment]
I can try but I'm not a php dev.  Which plugin is going to be supported going forward?  The snipcart plugin or shoppingcart plugin?  I don't see subscription support in shoppingcart-stripe

**Comment by rhukster** [comment]
`snipcart` is the one the Grav team put together.  `shoppingcart` is a 3rd party plugin

**Comment by jeubanks** [comment]
I was wondering which was which.

**Comment by bredmor** [comment]
I have an open pull request that will fix this issue still. https://github.com/getgrav/grav-plugin-snipcart/pull/22
