### ISSUE TITLE
Disabling "Use built-in CSS"

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-snipcart#6]
If I disable "Use built-in CSS", how do I specify the CSS file to use without hacking the plugin?

If I hack the plugin/css, they get overwritten when plugin is updated.

Maybe a feature request to have a field in the plugin settings to add `/path/to/custom.css`

**Comment by rhukster** [comment]
The intention is you turn off the built-in css provided by the plugin and provide your own in your theme.  So no hacking needed, just provide a theme-specific css file for this stuff in your theme itself.

**Comment by ghost** [comment]
Yeah, but... it's not "theme-specific" it's "plugin-specific".

Ah forget it.
